site_name: BMEVIAUAC01 Adatvezérelt rendszerek
site_author: Dudás Ákos
copyright: Copyright &copy; BME VIK AUT
repo_name: bmeviauac01/adatvezerelt
repo_url: https://github.com/bmeviauac01/adatvezerelt

theme:
  name: material
  language: hu
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Váltás sötét témára
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/lightbulb
        name: Váltás világos témára
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - search.suggest   
  logo: img/logo-bme-aut.png
  favicon: img/favicon.ico

extra_css:
  - extra-material-theme.css

extra:
  generator: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search:
      prebuild_index: true

nav:
  - index.md
  - "Adatbázis":
      - db/index.md
      - db/mssql.md
      - db/mongodb.md
      - "Minta adatbázis: mssql.sql": https://raw.githubusercontent.com/bmeviauac01/adatvezerelt/master/docs/db/mssql.sql
      - "Minta adatbázis: mongo.js": https://raw.githubusercontent.com/bmeviauac01/adatvezerelt/master/docs/db/mongo.js
  - "Jegyzetek":
      - jegyzet/architektura/index.md
      - jegyzet/transactions/index.md
      - jegyzet/mssql/sql.md
      - jegyzet/mssql/server-side-programming.md
      - jegyzet/linq/index.md
      - jegyzet/ef/index.md
      - jegyzet/mongodb/index.md
      - jegyzet/di/index.md
      - jegyzet/async/index.md
      - "REST és WebAPI demó alkalmazás (GitHub)": https://github.com/bmeviauac01/rest-webapi-sample
      - "ASP.NET Core DI demó alkalmazás (GitHub)": https://github.com/bmeviauac01/todoapi-di-sample
      - "Minta többrétegű webalkalmazás (GitHub)": https://github.com/bmeviauac01/threelayered-aspnetcore-sample
  - "Gyakorlatok":
      - gyakorlat/transactions/index.md
      - gyakorlat/mssql/index.md
      - gyakorlat/ef/index.md
      - gyakorlat/mongodb/index.md
      - gyakorlat/jpa/index.md
      - gyakorlat/rest/index.md
  - "Házi feladatok":
      - hazi/index.md
      - hazi/mssql/index.md
      - hazi/adonet/index.md
      - hazi/ef/index.md
      - hazi/mongodb/index.md
      - hazi/rest/index.md
      - hazi/GitHub.md
      - hazi/GitHub-Actions.md
      - hazi/VisualStudio.md
